name: CalcAdapter manual trigger
on: 
  workflow_dispatch
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repositor
        uses: actions/checkout@v1
        
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
    
      - name: Install newman
        run: | 
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          
#######################################################          

      - name: test PublicSOAP_APIs POSTMAN collection
        working-directory: ./PublicSOAP_APIs
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: |
          echo $CLIENT_SECRET
          echo $CLIENT_ID
          mkdir -p PublicSOAPtestResults
          newman run PublicSOAPAPIs.postman_collection.json -e publicSOAP.postman_environment.json -r htmlextra --reporter-htmlextra-export PublicSOAPtestResults/htmlreport.html --reporter-htmlextra-darkTheme  > PublicSOAPtestResults/runreport1.html
    
      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports_PublicSOAP_APIs
          path: ./PublicSOAP_APIs/PublicSOAPtestResults

################################################

      - name: test BookCartAPI POSTMAN collection
        working-directory: ./BookCartAPI
        run: |
          mkdir -p BookCarttestResults
          newman run BookCartAPI.postman_collection.json -e bookcart.postman_environment.json -r htmlextra --reporter-htmlextra-export BookCarttestResults/htmlreport.html --reporter-htmlextra-darkTheme  > BookCarttestResults/runreport1.html

      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports_BookCartAPI
          path: ./BookCartAPI/BookCarttestResults

###############################################

      - name: test LibraryAPI POSTMAN collection
        working-directory: ./LibraryAPI
        run: |
          mkdir -p LibrarytestResults
          newman run LibraryAPIReference.postman_collection.json -e library.postman_environment.json -r htmlextra --reporter-htmlextra-export LibrarytestResults/htmlreport.html --reporter-htmlextra-darkTheme  > LibrarytestResults/runreport1.html
    
      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports_BookCartAPI
          path: ./LibraryAPI/LibrarytestResults
      
